name: Build Mips-musl Nightly Releases
on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-mips-musl-nightly-release:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    strategy:
      fail-fast: false
      matrix:
        target:
          - mipsel-unknown-linux-musl

    steps:
      - name: Checkout the code
        uses: actions/checkout@v6

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          bash <(curl --proto '=https' --tlsv1.2 -sS ${{ secrets.RUSTUP }})

      - name: Install upx
        run: |
          wget https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-amd64_linux.tar.xz
          tar Jxf upx-4.2.4-amd64_linux.tar.xz
          sudo install -m 755 upx-4.2.4-amd64_linux/upx /usr/bin/upx
          rm -rf upx-4.2.4-amd64_linux*

      - name: Build ${{ matrix.target }}
        timeout-minutes: 120
        run: |
          cd ..
          [ "${{ matrix.target }}" = "mips-unknown-linux-musl" ] && target=mips || target=mipsel
          export $(echo "CARGO_TARGET_$(echo "$target" | tr '[:lower:]' '[:upper:]')_UNKNOWN_LINUX_MUSL_LINKER"="$target-openwrt-linux-musl-gcc")
          CARGO_BUILD_TARGET=${{ matrix.target }} \
          CARGO_HOME=install \
          RUSTFLAGS="-Ctarget-feature=-crt-static -lssp_nonshared -Clink-arg=-fuse-ld=bfd" \
          TARGET_CC=$target-openwrt-linux-musl-gcc \
          cargo +nightly install \
            -Z build-std=core,alloc,std,panic_abort \
            --target mipsel-unknown-linux-musl \
            --features "full" \
            --profile release \
            --path "shadowsocks-rust"
        
          upx -9 install/bin/*
          tar -Jcf shadowsocks-rust-${{ github.ref_name }}-$(echo ${{ github.sha }} | cut -c1-7)-${{ matrix.target }}.tar.xz -C install/bin .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: shadowsocks-rust-${{ github.ref_name }}-$(echo ${{ github.sha }} | cut -c1-7)-${{ matrix.target }}
          path: shadowsocks-rust-${{ github.ref_name }}-$(echo ${{ github.sha }} | cut -c1-7)-${{ matrix.target }}.tar.xz
